---
- name: Create a directory for the database restore to live.
  file:
    path: '{{ backup_dir.rstrip("/") }}/restore/'
    mode: 0775
    owner: root
    state: directory
  notify: Remove the restore directory.

- name: Upload the backup tarball to the server.
  copy:
    dest: '{{ backup_dir.rstrip("/") }}/restore/tower-restore.tar.gz'
    mode: 0664
    owner: root
    src: '{{ restore_backup_file }}'

- name: Uncompress the backup file.
  shell: tar xvfz tower-restore.tar.gz
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'

- name: Check for a host specific directory
  stat:
    path: '{{ backup_dir.rstrip("/") }}/restore/{{ inventory_hostname }}.tar.gz'
  register: host_archive

- name: Register presence of host archive
  set_fact:
    has_host_archive: host_archive.stat.exists

- name: Extract the common archive.
  shell: tar xvfz common.tar.gz
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'

- name: Extract the host specific archive
  shell: 'tar xvfz {{ inventory_hostname }}.tar.gz'
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'
  when: has_host_archive

- name: Stop Web Service.
  service:
    name: '{{ web_service_name }}'
    state: stopped
  notify: start web service.

- name: Stop supervisor.
  service:
    name: '{{ supervisor_service_name }}'
    state: stopped
  notify: start supervisord.

- name: Get tower db settings
  shell: "awx-manage print_settings | grep '^DATABASES'"
  register: results
  changed_when: False
  no_log: True

- name: Ingest database settings
  set_fact:
    tower_db_settings: "{{ results.stdout | regex_replace('DATABASES\\s+= ', '') }}"
  no_log: True
